name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      # Cache Buildozer global directory
      - name: Cache Buildozer global
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache Buildozer build directory
      - name: Cache Buildozer
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      # Build APK with Buildozer
      - name: Build with Buildozer
        id: buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: stable

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app-apk
          path: ${{ steps.buildozer.outputs.filename }} 
